export const environment = {
   production: true,
   url: "https://domiruth-uat.azure-api.net/security/",
   url_2: "https://domiruth-uat.azure-api.net/flight/",
   url_5: 'https://domiruth-uat.azure-api.net/customer/',
   url_6: 'https://domiruth-uat.azure-api.net/notify/',
   url_hotel: "https://domiruth-uat.azure-api.net/hotel/",
   url_project :"http://sigvplus.azurewebsites.net",
   cod_rol_autogestion: [1],
   cod_rol_autorizador: [2],
   cod_rol_centralizador: [3],
   max_pax: 8,
   url_bnus: 'https://ws-bnu.domiruth.com/api/',
  key: "eb85131bc9d94c02840aa6961e7f77e9"
/* production: true,
  url: "https://domiruth-prd.azure-api.net/security/",
  url_2: "https://domiruth-prd.azure-api.net/flight/",
  url_5: 'https://domiruth-prd.azure-api.net/customer/',
  url_6: 'https://domiruth-prd.azure-api.net/notify/',
  url_hotel: "https://domiruth-prd.azure-api.net/hotel/",
  url_project : "https://localhost:4200",
  cod_rol_autogestion: [1],
  cod_rol_autorizador: [2],
  cod_rol_centralizador: [3],
  max_pax: 8,
  url_bnus: 'https://ws-bnu.domiruth.com/api/',
  key: '78e06a82cb2e4ddfb445f10d4ac6b36e'*/
};
