export interface ISearchFlightModel {
  recommendationId;
  currency;
  totalFareAmount;
  totalTaxAmount;
  fareAmountByPassenger;
  taxAmountByPassenger;
  fareTaxAmountByPassenger;
  carrierId;
  plaqueadoresId;
  numberPassengers;
  pseudo;
  pseudoRepeat;
  priceByPseudo;
  ltaxDetails;
  lsections;
  lpolicies;
  gds;
  isVisible;
}
